package com.pikolic.meli.entity;

import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

/**
 * JPA entity representing a client in the Meli e-commerce system.
 * <p>
 * This entity maps to the {@code client} table in the database and contains
 * the personal information of a client, including their name, age, email,
 * and address. It also maintains a one-to-many relationship with {@link OrderEntity},
 * representing all orders associated with this client.
 * </p>
 *
 * <p>Relationship details:</p>
 * <ul>
 *     <li>{@link #orders}: One {@code ClientEntity} can have multiple {@link OrderEntity} objects.</li>
 *     <li>{@code cascade = CascadeType.PERSIST}: Persist operations on the client will cascade to orders.</li>
 *     <li>{@code orphanRemoval = true}: Removing an order from the list will delete it from the database.</li>
 * </ul>
 *
 * <p>Lombok annotations:</p>
 * <ul>
 *     <li>{@link Getter} / {@link Setter}: Automatically generates getters and setters for all fields.</li>
 *     <li>{@link Builder}: Provides a fluent builder API for creating instances.</li>
 *     <li>{@link NoArgsConstructor} / {@link AllArgsConstructor}: Generates constructors with no arguments and with all arguments.</li>
 * </ul>
 *
 * @author Angel Lomelí
 * @see OrderEntity
 */
@Entity
@Table(name = "client")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ClientEntity {

    /** Unique identifier for the client. Auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** The full name of the client. Cannot be null. */
    @Column(nullable = false)
    private String name;

    /** The age of the client. Cannot be null. */
    @Column(nullable = false)
    private Integer age;

    /** The email address of the client. Cannot be null. */
    @Column(nullable = false)
    private String email;

    /** The physical address of the client. Optional. */
    private String address;

    /**
     * List of orders associated with the client.
     * <p>
     * One-to-many relationship with {@link OrderEntity}.
     * Cascade persists new orders when the client is saved, and orphanRemoval
     * ensures that removed orders are deleted from the database.
     * </p>
     */
    @OneToMany(mappedBy = "client", cascade = CascadeType.PERSIST, orphanRemoval = true)
    private List<OrderEntity> orders = new ArrayList<>();
}
